name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake -B ${PWD}/build/ -D CMAKE_BUILD_TYPE="Debug" -G Ninja
    - name: build
      run: ninja -C build/
