name: Docker Image CI

on:
  push:
    branches: [ "main", "benchmarks" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Get tag
      id: date
      run: echo "::set-output name=date::$(date +'%s')"

    - name: Build the Docker image
      run: docker build -t mwe:${{ steps.date.outputs.date }} --target=release .

    - name: Run unittests
      run: docker run --rm --gpus all mwe:${{ steps.date.outputs.date }} sh -c 'cd /src/mwe/build && ctest --verbose'

    - name: Run benchmark
      run: docker run --rm --gpus all mwe:${{ steps.date.outputs.date }} sh -c '/src/mwe/build/benchmarks/matmul_benchmark --benchmark_format=json' | tee output.txt
