name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unittests:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Get tag
      id: date
      run: echo "::set-output name=date::$(date +'%s')"

    - name: Build the Docker image
      run: docker build -t mwe:${{ steps.date.outputs.date }} --target=release .

    - name: Run unittests
      run: docker run --rm --gpus all mwe:${{ steps.date.outputs.date }} sh -c 'ctest --test-dir /src/mwe/build'
